Reestruturando arquitetura do projeto
guildatech/awesome-projects pull request #10
Opened 2018-10-01 13:56 UTC by iagocavalcante

Proposta para reestruturação de pastas, separando o projeto para deixar pronto para ter um frontend e backend melhor organizado

2018-10-02 11:07 UTC, jcserracampos requested changes
Quando você alterou a estrutura de pastas, não alterou o caminho em que os projetos estão no arquivos `getProject.js`.
Na linha 14 está `const files = await glob('projetos/*.md');`.
O correto seria `const files = await glob('../projetos/*.md');`.
Talvez seja interessante fazer uma pasta public para armazenar essas coisas.

2018-10-02 11:10 UTC, iagocavalcante commented
Deixei desse jeito, pois havia testado e continuou funcionando. Posso colocar ela dentro da pasta public dentro do server, o que você acha ?

2018-10-02 11:15 UTC, jcserracampos commented
Eu acho que a pasta projetos tem que ficar na raiz do projetos para facilitar que enviem PRs adicionando novos.
Apesar de que a maioria das pessoas que submeterão projetos terão conhecimento de Github, podem ficar perdidas para achar a pasta projetos.

2018-10-02 11:17 UTC, iagocavalcante commented
Por isso deixei lá, vou fazer a alteração só onde é necessário e envio.

2019-09-24 13:33 UTC, jcserracampos approved these changes

2019-09-26 13:15 UTC, merged

2019-09-26 13:16 UTC, jcserracampos commented
Muito obrigado pelo seu PR, @iagocavalcante